[package]
name = "httpdrs-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "httpdrs_core"
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
reqwest = { workspace = true }

# logger dependencies
tracing = { workspace = true }
tracing-subscriber = { workspace = true }