[package]
name = "httpdrs-logger"
version = "0.1.0"
edition = "2024"

[lib]
name = "httpdrs_logger"
path = "src/lib.rs"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
